### ISSUE TITLE
Rotation crash

### ISSUE THREAD

**Issue by eevleevs** [avuton/HayaiLauncher#2] opened 2017-06-17 12:17 UTC
Hi, I am getting this error at reboot and at every rotation. Happens when Xposed module XTouchWiz is active. Any idea?

06-17 11:49:01.971 5507-5507/com.hayaisoftware.launcher E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.hayaisoftware.launcher, PID: 5507
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
                                                                              at android.app.ResourcesManager.applyConfigurationToResourcesLocked(ResourcesManager.java:605)
                                                                              at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5815)
                                                                              at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:5730)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1944)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7407)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                              at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by avuton** [comment] 2017-06-17 14:03
Hi,

I have no real idea how this is broken, I really doubt it's a bug that I could even workaround. I'm enjoying speculating what the cause is.

I've got a couple of theories. If you're really interested, you could try to install `master` (assuming you're not using the master branch right now). If that doesn't work, you could try the `xp1` branch. If neither of those fix it, you could run a `git bisect` to find where the problem begins.

**Comment by avuton** [comment] 2017-06-17 14:56
When I said `master` I should have said `51a7df2a4`. I'm going to be merging some `next` stuff to `master` soon.

**Comment by avuton** [comment] 2017-06-17 16:29
Finally, let me know if there is anything I can do to help. I'm interested in where the bug actually is, out of curiosity. I do doubt there's much I could do to workaround the issue. Closing for now, feel free to open it back up if there's anything else to add here.

**Closed by avuton** 2017-06-17 16:29 UTC

**Comment by eevleevs** [comment] 2017-06-17 17:45
Actually it is not a problem of your code. The original Hayai fails the same way. 

Why do you say there is nothing to do? Is it a bug of the SDK?

**Comment by avuton** [comment] 2017-06-17 20:17
I was trying to say there's not much I can do in my code. I wouldn't say it was a bug of the SDK, and this is my naïve view of Xposed, but some kind of mutation they're doing to the SDK.

**Comment by eevleevs** [comment] 2017-06-17 20:32
Probably... but still it is the only app failing this way. I wonder why. 
Another thing I forgot: it fails also if it is not in foreground.

Thanks for the discussion anyway.
